### ISSUE TITLE
While building application getting error

### ISSUE THREAD

**Issue by nissarcs** [samkelleher/cordova-plugin-applepay#1]
While i am trying to build application am getting below errors
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/---/---/platforms/ios/cordova/build-debug.xcconfig,-project,applpay.xcodeproj,ARCHS=i386,-target,applpay,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/smgadmin/nissarapplepay/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/smgadmin/nissarapplepay/platforms/ios/build/sharedpch

**Comment by samkelleher** [comment]
It's not possible to replicate or debug this issue without more information.

On first glance, I see that the architecture should be armv7 arm64.

Ensure you are running the minimum supported Cordova (6), iOS Cordova Platform (4) and XCode (7.3.1).

I'll close this issue for now.  If you have more information please add and re-open.
