### ISSUE TITLE
Not working on iOS 10

### ISSUE THREAD

**Issue by Jamesmallon1** [samkelleher/cordova-plugin-applepay#11]
Is this working on iOS 10?

I keep receiving the following error:
"This device can make payments but has no supported cards."

I am using phonegap build and this is my config.xml:
`<plugin name="cordova-plugin-applepay-stripe" source="npm">
    <param name="STRIPE_TEST_PUBLISHABLE_KEY" value="pk_live_sCgKeifQ0CJQHEmu2ogFXRDR" />
    <param name="STRIPE_LIVE_PUBLISHABLE_KEY" value="pk_test_sCgKeifQ0CJQHEmu2ogFXRDR" />
    <param name="APPLE_MERCHANT_IDENTIFIER" value="this is correct id here." />
	</plugin>`

This happens on both yours and the forked one above.
Any help?

James

**Comment by samkelleher** [comment]
Hello @Jamesmallon1 , yes iOS10 is working normally as there were no API changes in this iOS release from iOS9.

This error is described on the projects readme.

> If in your catch you get the message This device can make payments but has no supported cards - you can decide if you want to handle this by showing the 'Setup Apple Pay' buttons instead of the normal 'Pay with Apple Bay' buttons as per the Apple Guidelines.

Your simulator/device is not setup for Apple Pay so you should check your apps configuration, such as checking that your project and bundle are enabled correctly.

If you are using the forked version that has Stripe added then try raising an issue there.

**Comment by Jamesmallon1** [comment]
Hi @samkelleher,

My device is set up for apple pay. I believe I have narrowed down the issue. I am using phonegap build but I have no way of setting my entitlements to turn apple pay on. Is this something you can look into? I know other plugins like phonegap-plugin-push provides the entry in to the entitlements plist.

James
