### ISSUE TITLE
Symbol Not Found

### ISSUE THREAD

**Issue by cincaw** [samkelleher/cordova-plugin-applepay#16]
Hi, after I Install the plugin and try to build on my iPhone I got error message "Symbol not found" in my xCode, here is the complete error log. Thanks

Error :
dyld: Symbol not found: _kABPersonAddressCityKey
  Referenced from: /var/containers/Bundle/Application/384FF26E-B485-4792-9CDD-4552E6E184A6/star.app/star
  Expected in: /System/Library/Frameworks/PassKit.framework/PassKit
 in /var/containers/Bundle/Application/384FF26E-B485-4792-9CDD-4552E6E184A6/star.app/star
(lldb)

**Comment by samkelleher** [comment]
Hello @cincaw  -  thanks for stopping by, have you followed the Apple instructions to enable Apple Pay within your application.  The `PassKit.framework` is not being Linked. This is outside the scope of the plugin so you should check your cordova build configuration is setup correctly.

Thanks.
