### ISSUE TITLE
Install does not work

### ISSUE THREAD

**Issue by hsmith825** [samkelleher/cordova-plugin-applepay#2]
When I install with cordova plugin add cordova-plugin-applepay, I get a plugin from nam with the following methods: getAllowsApplePay, setMerchantId.

I do not get the methods in this plugin. 

Any ideas to sole this problem?

**Comment by hsmith825** [comment]
I am using Cordova version 6.0.0 and Xcode 7.3.1
I also tried to install with add cordova-plugin-applepay @2.1.3 .  I get npm ERR! addLocal Could not install /Users/howardsmith/.Trash/Flickitt23 12.10.52 PM/@2.1.3
Error: Failed to fetch plugin @2.1.3 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.

The link /Users/howardsmith/.Trash/Flickitt23 is to the previous

Thanks! version of my app that I trashed in search of a solution to this problem.

**Comment by hsmith825** [comment]
Some reason my Local nam loaded an the wrong plugin.  I have loaded the correct plugin.  However, I can not build.  I am getting lots of errors on CDVApplePay.m.  I think they are related to this error:  @import AddressBook;    Use of @inport when modules are disabled.

Any Help is appreciated!!!

**Comment by hsmith825** [comment]
for anyone else that has the problem, Go to build settings and enable modules.  Now I can install.

**Comment by samkelleher** [comment]
@hsmith825 Maybe follow up with the version of the iOS platform.

For me, a Cordova app based on the platform 4.1.1 already has the `Enable Modules (C and Objective-C)` enabled. I didn't need to enable it specifically to get Apple Pay to work. Maybe another plugin you're using has disabled it.
