### ISSUE TITLE
"This device can make payments but has no supported cards" but APPLE test cards have been added

### ISSUE THREAD

**Issue by harishios** [samkelleher/cordova-plugin-applepay#22]
Hi,
Once this plugin is integrated as below,
`   
    
    //Check if the device can make payment.
    ApplePay.canMakePayments()
    .then((message) => {
       alert(message);
       this.applePayRequestForPayment();
    })
    .catch((message) => {
      alert(message);
    });
  }`

 "This device can make payments but has no supported cards" message when checking availability yet a few test cards have been added and are visible in the wallet. Sample cards have been selected from this page h[ttps://developer.apple.com/support/apple-pay-sandbox/](url) 
Device is iPhone 6+ running iOS 11

**Comment by CookieCookson** [comment]
Hey @harishios - I've just started having a play with this plugin on a test project and encountered the same issue. Did you find a way to resolve the issue? Have you tried testing with a device on iOS 10?

**Comment by harishios** [comment]
Hi @CookieCookson 

You need to select the Merchant ID in your Apple Developer Account and Add the same in XCode Capabilities and MAKE SURE YOU make that ID TICK(BLUE COLOR). Then it will work for sure, please find the image for your reference.
<img width="664" alt="screen shot 2017-11-24 at 7 07 17 pm" src="https://user-images.githubusercontent.com/18008999/33212872-edc821b4-d14a-11e7-855f-6fc398ab926e.png">

**Comment by CookieCookson** [comment]
Thanks for your reply @harishios - I had the Apple Pay capability ticked already, but my Merchant ID was not ticked. However, even after ticking that box I have had no success on my device - it still claims "This device can make payments but has no supported cards". The assigned card is a VISA card.

**Comment by harishios** [comment]
Please logout from the Apple iCloud Account from your device. Make sure you have Logged in with the same Apple Sandbox Account in device

**Comment by CookieCookson** [comment]
I'm trying it with a production card/account on my device - do I need to use a sandbox account for apps signed with a development certificate?

**Comment by ajcrites** [comment]
Closing as this does not appear to be related to the plugin.

**Comment by Ghayyas** [comment]
Same issue with me. I have already login with sandbox credentials
My IOS version 14.6
