### ISSUE TITLE
MyPaymentProvider.authorizeApplePayToken not working

### ISSUE THREAD

**Issue by vkrntteotia** [samkelleher/cordova-plugin-applepay#29]
After payment response, what is the following provider?

```
// Here is an example implementation:

        // MyPaymentProvider.authorizeApplePayToken(token.paymentData)
        //    .then((captureStatus) => {
        //        // Displays the 'done' green tick and closes the sheet.
        //        ApplePay.completeLastTransaction('success');
        //    })
        //    .catch((err) => {
        //        // Displays the 'failed' red cross.
        //        ApplePay.completeLastTransaction('failure');
        //    });
```

And what I need to define here?

Payment response for makepaymentrequest() is : 
`{"paymentMethodNetwork":"MasterCard","paymentMethodDisplayName":"Simulated Instrument","paymentData":"","paymentMethodTypeCard":"unknown","transactionIdentifier":"Simulated Identifier"}`

It didn't respond any token. Then what I need to pass next?

**Comment by ajcrites** [comment]
If you are using a simulated card `paymentData` will always be an empty string. You must use a real card on a real device to get real payment data.
