### ISSUE TITLE
Where to specify the payment gateway information

### ISSUE THREAD

**Issue by zhangzhang** [samkelleher/cordova-plugin-applepay#3]
As I understand, the apple pay has to work with a payment gateway, I choose stripe, but I don't see anywhere in this cordova plugin that I could specify the gateway keys and tokens, the document of the payment gateway requires to have those info integrated with the app:
https://stripe.com/docs/mobile/ios
Could you please help me to point out where in the code that I could set the token or keys?

**Comment by samkelleher** [comment]
Hi @zhangzhang,

This plugin can work with any payment gateway, the installation of a provider SDK and connecting it is not part of the scope of this plugin. Consult the documentation for the Stripe API or SDK.

The plugin simply exposes an authorised Apple Pay token to your application at JavaScript level. You would need to relay this token to Stripe yourself, either using their SDK or make a call directly using their API.

```
 stripe.authorizeApplePayToken(token.paymentData)
  .then((captureStatus) => {
       // Displays the 'done' green tick and closes the sheet.
       ApplePay.completeLastTransaction('success');
  })
  .catch((err) => {
       // Displays the 'failed' red cross.
       ApplePay.completeLastTransaction('failure');
  });
```

Thanks for stopping by.
