### ISSUE TITLE
Is there is any way to use this plugin for Apple Wallet

### ISSUE THREAD

**Issue by tomavic** [samkelleher/cordova-plugin-applepay#33]
I need to add my credit cards through my app to Apple Wallet. How to do this using this plugin? HELP

**Comment by ajcrites** [comment]
This plugin doesn’t have a way to add cards to the wallet. You will have to use a different plugin for that.

**Comment by tomavic** [comment]
I searched the internet, but there is no plugin for such use case. Is there is any help you can provide for that ?

**Comment by ajcrites** [comment]
You can try https://github.com/passslot/cordova-plugin-passbook

**Comment by tomavic** [comment]
Yeah that one :( 

I had asked them for support or advise but no replay !

I have full support from Apple itself on how to implement this feature, but all documentation are for Native implementation, and I need a cordova plugin to implement it

I don't know what to do, could you help on that

**Comment by ajcrites** [comment]
Sorry, I’ve never used the passbook or Apple wallet.

**Comment by tomavic** [comment]
I don't mean that, **I mean help on how to create custom plugin using objective-C**. My company already have a deal with Apple Inc. to implement this feature, but unfortunately Apple doesn't support cross-platform development and they don't have description on how to do this in a plugin

**Comment by ajcrites** [comment]
Refer to Cordova’s own documentation. https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/
