### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by syn6UK** [samkelleher/cordova-plugin-applepay#35]
Not sure if its the ionic devapp but when i trigger makePaymentRequest nothing actually happens. Doesn't error or even console log a result. Does it work in ionic devapp?

**Comment by syn6UK** [comment]
Ah ok so it says on console log plugin not installed but as you can see its clearly installed...


`[app-scripts] [16:55:33]  console.warn: Native: tried calling ApplePay.makePaymentRequest, but the ApplePay plugin is not installed. 
[app-scripts] [16:55:33]  console.warn: Install the ApplePay plugin: 'ionic cordova plugin add cordova-plugin-applepay' 
[app-scripts] [16:55:33]  console.error: Error plugin_not_installed 

C:\Users\Robert.Lane\WebstormProjects\hipzionic\hipz>ionic cordova plugin add cordova-plugin-applepay
> cordova plugin add cordova-plugin-applepay --save
Plugin "cordova-plugin-applepay" already installed on ios.
Adding cordova-plugin-applepay to package.json
Saved plugin info for "cordova-plugin-applepay" to config.xml
`

**Comment by samkelleher** [comment]
A clean/rebuild should help here.
