### ISSUE TITLE
Empty paymentData in response

### ISSUE THREAD

**Issue by Stasyan123** [samkelleher/cordova-plugin-applepay#36]
Hello 
when calling the makePaymentRequest function, a confirmation of payment view is displayed, but after pressing the button "Pay with passcode" in the response, the property of paymentData comes with an empty string. Can i get BASE64 ENCODED TOKEN using a simulator?
Thank you in advance for your cooperation

**Comment by ajcrites** [comment]
Not that I know of. I think you need to deploy to a device with a test merchant and certificate.

**Comment by Stasyan123** [comment]
Okay, thanks a lot for your help
