### ISSUE TITLE
makePaymentRequest nothing happens

### ISSUE THREAD

**Issue by patrickchoi** [samkelleher/cordova-plugin-applepay#37]
The Apple Pay window doesn't appear, and nothing appears in my console either.

I tried both simulator and a device but nothing happens. 

Installation seemed to go fine. I added ApplePay in Providers of app.module.ts and I see no messages about the plugin missing.

**Comment by patrickchoi** [comment]
Solved it. Needed to config the Apple Pay in Capabilities section in Xcode with the Merchant ID.

**Comment by ajcrites** [comment]
Closing as this seems to be resolved.
