### ISSUE TITLE
Cards not added in Stripe Account

### ISSUE THREAD

**Issue by raghavdm** [samkelleher/cordova-plugin-applepay#39]
I have implement this plugin. All are working properly but the problem is, in stripe customer is created successfully but he doesn't have any card details under his account so that why stripe charges api is giving error:-

{
  "error": {
    "code": "missing",
    "doc_url": "https://stripe.com/docs/error-codes/missing",
    "message": "Cannot charge a customer that has no active card",
    "param": "card",
    "type": "card_error"
  }
}

**Comment by samkelleher** [comment]
Thanks for commenting.  This isn't a Stripe plugin, it's for Apple Pay only. The handling of the token this plugin generates to Stripe isn't part of this project and you should consult the separate Stripe SDK for details.
