### ISSUE TITLE
Does not work with iOS 12

### ISSUE THREAD

**Issue by davidsiers** [samkelleher/cordova-plugin-applepay#40]

**Comment by samkelleher** [comment]
Can you be more specific as to what error (if any) you have?

**Comment by samkelleher** [comment]
@hiteshr882 Please review the documentation on the projects README. The is an Apple Pay plugin, not a Stripe plugin. This plugin does not handle Stripe Tokens. For that you should consult the Stripe SDK. Stripe is not the same as Apple Pay.  If you are receiving a null token value after `makePaymentRequest` then you're application is not enabled for Apple Pay and you should check the entitlements and rebuild as necessary.

**Comment by kingkarki** [comment]
I m getting this error `KPaymentRequest must contain an NSArray property 'paymentSummaryItems' of at least 1 valid objects of class PKPaymentSummaryItem}`
