### ISSUE TITLE
Payment Response not returning stripetoken

### ISSUE THREAD

**Issue by DNeelanshi** [samkelleher/cordova-plugin-applepay#41]
###  **I am using this plugin and sending this request:**
var paymentRequestOptions:any = {
        items:[
            {
                label: data.artistname,
                amount: data.price
            }
        ],
        shippingMethods: [
            {
                identifier: 'NextDay',
                label: 'NextDay',
                detail: 'Arrives tomorrow by 5pm.',
                amount: 0
            }
        ],
        merchantIdentifier: 'merchant.com.appid',
        currencyCode: 'USD',
        countryCode: 'US',
        billingAddressRequirement: 'none',
        shippingAddressRequirement: 'none',
        shippingType: 'shipping'
  }; 
### **its returning me payment Response -** 

"transactionIdentifier":"807E8FA86FDD26682D9C7EFF042F459002746E798DDEAC97C730BBE1BB9B5F13","paymentData":"eyJ2ZXJzaW9uIjoiRUNfdjEiLCJkYXRhIjoiMkF0a1FkM1JPdTZTc2hISTNkZ1llMXBNazIyR0QzQk1FMVFleFFxSFNHNXZQUHBsT2RXb0lKOW9CT2RDVkFsSENBWXRmaWpvanZwUHh2L3ROcWxKdjEvaERvdHdTeFByM1diRFVFbnArSlZSSVd0M1FQOHdtdWt5cm1kK3VaeGpNVW93V2tmdXRGZlRCdzNCemtmS2FEYmZ4Yld6cFhKeU9RUWQ2Rm1yWlNyUnVNdXlIUWxGdXlrOHZ5cjZOMXg0UmVxSTRuM0VRaDdiSUE5NEdYZzMwY3FkZXd5QWRrU1luK1ZWQnNZS0pkb29zSzA0TkNYWGFuVXRub3NoZHJua0pBNHJmSnJTdzZob2lBeW5HL25wWGdTU3BYWHNJeGNhR3hZT2grTXRMTFNvdTBRdnFRaVAramxqdGVrZzllTWxKVWNBVVhZMG5Pc1BkRDFyRTkycHRIeTQ0dEl6VWd2Szc3bjNLM1JQSzAzRXhSM0I4aVUvV1k5SjNYcmNDWitUdWQ4cnlpdVlHNGlxK2F6VTBRWE5lelRQSkp5MkNYREtzZE5xMlQ0YXJnPT0iLCJzaWduYXR1cmUiOiJNSUFHQ1NxR1NJYjNEUUVIQXFDQU1JQUNBUUV4RHpBTkJnbGdoa2dCWlFNRUFnRUZBRENBQmdrcWhraUc5dzBCQndFQUFLQ0FNSUlENGpDQ0E0aWdBd0lCQWdJSUpFUHlxQWFkOVhjd0NnWUlLb1pJemowRUF3SXdlakV1TUN3R0ExVUVBd3dsUVhCd2JHVWdRWEJ3YkdsallYUnBiMjRnU1c1MFpXZHlZWFJwYjI0Z1EwRWdMU0JITXpFbU1DUUdBMVVFQ3d3ZFFYQndiR1VnUTJWeWRHbG1hV05oZEdsdmJpQkJkWFJvYjNKcGRIa3hFekFSQmdOVkJBb01Da0Z3Y0d4bElFbHVZeTR4Q3pBSkJnTlZCQVlUQWxWVE1CNFhEVEUwTURreU5USXlNRFl4TVZvWERURTVNRGt5TkRJeU1EWXhNVm93WHpFbE1DTUdBMVVFQXd3Y1pXTmpMWE50Y0MxaWNtOXJaWEl0YzJsbmJsOVZRelF0VUZKUFJERVVNQklHQTFVRUN3d0xhVTlUSUZONWMzUmxiWE14RXpBUkJnTlZCQW9NQ2tGd2NHeGxJRWx1WXk0eEN6QUpCZ05WQkFZVEFsVlRNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUV3aFYzN2V2V3g3SWhqMmpkY0pDaElZM0hzTDF2TENnOWhHQ1YyVXIwcFVFYmcwSU8yQkh6UUg2RE14OGNWTVAzNnpJZzFyclYxTy8wa29tSlBud1BFNk9DQWhFd2dnSU5NRVVHQ0NzR0FRVUZCd0VCQkRrd056QTFCZ2dyQmdFRkJRY3dBWVlwYUhSMGNEb3ZMMjlqYzNBdVlYQndiR1V1WTI5dEwyOWpjM0F3TkMxaGNIQnNaV0ZwWTJFek1ERXdIUVlEVlIwT0JCWUVGSlJYMjIvVmRJR0dpWWwyTDM1WGhRZm5tMWdrTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVSS9KSnhFK1Q1TzhuNXNUMktHdy9vcnY5TGtzd2dnRWRCZ05WSFNBRWdnRVVNSUlCRURDQ0FRd0dDU3FHU0liM1kyUUZBVENCL2pDQnd3WUlLd1lCQlFVSEFnSXdnYllNZ2JOU1pXeHBZVzVqWlNCdmJpQjBhR2x6SUdObGNuUnBabWxqWVhSbElHSjVJR0Z1ZVNCd1lYSjBlU0JoYzNOMWJXVnpJR0ZqWTJWd2RHRnVZMlVnYjJZZ2RHaGxJSFJvWlc0Z1lYQndiR2xqWVdKc1pTQnpkR0Z1WkdGeVpDQjBaWEp0Y3lCaGJtUWdZMjl1WkdsMGFXOXVjeUJ2WmlCMWMyVXNJR05sY25ScFptbGpZWFJsSUhCdmJHbGplU0JoYm1RZ1kyVnlkR2xtYVdOaGRHbHZiaUJ3Y21GamRHbGpaU0J6ZEdGMFpXMWxiblJ6TGpBMkJnZ3JCZ0VGQlFjQ0FSWXFhSFIwY0RvdkwzZDNkeTVoY0hCc1pTNWpiMjB2WTJWeWRHbG1hV05oZEdWaGRYUm9iM0pwZEhrdk1EUUdBMVVkSHdRdE1Dc3dLYUFub0NXR0kyaDBkSEE2THk5amNtd3VZWEJ3YkdVdVkyOXRMMkZ3Y0d4bFlXbGpZVE11WTNKc01BNEdBMVVkRHdFQi93UUVBd0lIZ0RBUEJna3Foa2lHOTJOa0JoMEVBZ1VBTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUhLS253K1NveXE1bVhRcjFWNjJjMEJYS3BhSG9kWXU5VFdYRVBVV1BwYnBBaUVBa1RlY2ZXNitXNWwwcjBBRGZ6VENQcTJZdGJTMzl3MDFYSWF5cUJOeThiRXdnZ0x1TUlJQ2RhQURBZ0VDQWdoSmJTKy9PcGphbHpBS0JnZ3Foa2pPUFFRREFqQm5NUnN3R1FZRFZRUUREQkpCY0hCc1pTQlNiMjkwSUVOQklDMGdSek14SmpBa0JnTlZCQXNNSFVGd2NHeGxJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNU1STXdFUVlEVlFRS0RBcEJjSEJzWlNCSmJtTXVNUXN3Q1FZRFZRUUdFd0pWVXpBZUZ3MHhOREExTURZeU16UTJNekJhRncweU9UQTFNRFl5TXpRMk16QmFNSG94TGpBc0JnTlZCQU1NSlVGd2NHeGxJRUZ3Y0d4cFkyRjBhVzl1SUVsdWRHVm5jbUYwYVc5dUlFTkJJQzBnUnpNeEpqQWtCZ05WQkFzTUhVRndjR3hsSUVObGNuUnBabWxqWVhScGIyNGdRWFYwYUc5eWFYUjVNUk13RVFZRFZRUUtEQXBCY0hCc1pTQkpibU11TVFzd0NRWURWUVFHRXdKVlV6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQQVhFWVFaMTJTRjFScGVKWUVIZHVpQW91L2VlNjVONEkzOFM1UGhNMWJWWmxzMXJpTFFsM1lOSWs1N3VnajlkaGZPaU10MnUyWnd2c2pvS1lUL1ZFV2pnZmN3Z2ZRd1JnWUlLd1lCQlFVSEFRRUVPakE0TURZR0NDc0dBUVVGQnpBQmhpcG9kSFJ3T2k4dmIyTnpjQzVoY0hCc1pTNWpiMjB2YjJOemNEQTBMV0Z3Y0d4bGNtOXZkR05oWnpNd0hRWURWUjBPQkJZRUZDUHlTY1JQaytUdkorYkU5aWhzUDZLNy9TNUxNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdId1lEVlIwakJCZ3dGb0FVdTdEZW9WZ3ppSnFraXBuZXZyM3JyOXJMSktzd053WURWUjBmQkRBd0xqQXNvQ3FnS0lZbWFIUjBjRG92TDJOeWJDNWhjSEJzWlM1amIyMHZZWEJ3YkdWeWIyOTBZMkZuTXk1amNtd3dEZ1lEVlIwUEFRSC9CQVFEQWdFR01CQUdDaXFHU0liM1kyUUdBZzRFQWdVQU1Bb0dDQ3FHU000OUJBTUNBMmNBTUdRQ01EclBjb05SRnBteGh2czF3MWJLWXIvMEYrM1pEM1ZOb282KzhaeUJYa0szaWZpWTk1dFpuNWpWUVEyUG5lbkMvZ0l3TWkzVlJDR3dvd1YzYkYzek9EdVFaLzBYZkN3aGJaWlB4bkpwZ2hKdlZQaDZmUnVaeTVzSmlTRmhCcGtQQ1pJZEFBQXhnZ0dNTUlJQmlBSUJBVENCaGpCNk1TNHdMQVlEVlFRRERDVkJjSEJzWlNCQmNIQnNhV05oZEdsdmJpQkpiblJsWjNKaGRHbHZiaUJEUVNBdElFY3pNU1l3SkFZRFZRUUxEQjFCY0hCc1pTQkRaWEowYVdacFkyRjBhVzl1SUVGMWRHaHZjbWwwZVRFVE1CRUdBMVVFQ2d3S1FYQndiR1VnU1c1akxqRUxNQWtHQTFVRUJoTUNWVk1DQ0NSRDhxZ0duZlYzTUEwR0NXQ0dTQUZsQXdRQ0FRVUFvSUdWTUJnR0NTcUdTSWIzRFFFSkF6RUxCZ2txaGtpRzl3MEJCd0V3SEFZSktvWklodmNOQVFrRk1ROFhEVEU0TVRBek1ERXlNakV3TTFvd0tnWUpLb1pJaHZjTkFRazBNUjB3R3pBTkJnbGdoa2dCWlFNRUFnRUZBS0VLQmdncWhrak9QUVFEQWpBdkJna3Foa2lHOXcwQkNRUXhJZ1FnL0pxNkRWazM0RGM3ZUplOEcwWXZ2NzAxZ2ZJc1l2aU5FeHI2OWljdzB5Z3dDZ1lJS29aSXpqMEVBd0lFUnpCRkFpQUVhaEJMQ0I3K1gvZVBZS1pWOVpZZkNOWHhkZVk1ckMyRExNc2trQ25zc3dJaEFNSUduZHBrdlkwYmcrRmRJa2ZZOTZjeDN2d2ZOYklNV2FLc3BjSmZudllVQUFBQUFBQUEiLCJoZWFkZXIiOnsiZXBoZW1lcmFsUHVibGljS2V5IjoiTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFd2NpRVY2RWFHaXlxQW1PTFprUWljR1lMcDh3bzQyR3JabW9PMVlQc3djVnFCS2RhWUNKK1pmamtuRlRlRWdvcDdnekd2MXBpMUY0SmVDWGgvVTBUY0E9PSIsInB1YmxpY0tleUhhc2giOiJGN2lDdEpnbGJIWENQZW5UeHR4UUZjemwvMVZjWURpQVBDQTFud1pNbTZBPSIsInRyYW5zYWN0aW9uSWQiOiI4MDdlOGZhODZmZGQyNjY4MmQ5YzdlZmYwNDJmNDU5MDAyNzQ2ZTc5OGRkZWFjOTdjNzMwYmJlMWJiOWI1ZjEzIn19"}
**THERE IS NOT STRIPE TOKEN** .PLEASE HELP!. 
Thanks in advance.

**Comment by samkelleher** [comment]
As indicated in the projects ReadMe, the paymentData in the response is an Apple Pay Token. It is up to you to implement and consume this token with a provider of your choice. You can use Stripe, or any other merchant you choose.  If you want to use Stripe, you take this Apple Pay Token, and pass it along in their SDK, which is not part of this project.

Hope that clarifies.
