### ISSUE TITLE
Apple pay with stripe in ionic 3

### ISSUE THREAD

**Issue by darshansarvaiyasa** [samkelleher/cordova-plugin-applepay#45]
const success = await MyPaymentProvider.authorize(response.paymentData);

Please give more information about above line as i can't see this function in the code

**Comment by ajcrites** [comment]
This is just an example. Your payment provider would be Stripe, so use whatever SDK method they have that takes payment data to authorize payments. You will have to find this out from Stripe’s own documentation.

**Comment by darshansarvaiyasa** [comment]
Can you please 'makePaymentRequest' in this function return with stripe token as well so

**Comment by SRV-Garg** [comment]
@darshansarvaiyasa i am also facing the same problem did you find any solution?

**Comment by darshansarvaiyasa** [comment]
> @darshansarvaiyasa i am also facing the same problem did you find any solution?

Yes, in this function 'makePaymentRequest' return base64 token string, if plugin also return stripe token then problem solve.

**Comment by SRV-Garg** [comment]
@darshansarvaiyasa i know that but i don't know whether they are planning to do so or not so in meantime did you find anything to convert the paymentData response to stripe acceptable token?

**Comment by darshansarvaiyasa** [comment]
You can share me your code I will send you the code with updated corrections.
