### ISSUE TITLE
Cordova supported platforms lack suport for ES6 Promise

### ISSUE THREAD

**Issue by hsmith825** [samkelleher/cordova-plugin-applepay#5]
I have not used promises before.  I am getting snytactic errors in my cordova app.  Research indicates that Cordova supported platforms lack suport for ES6 Promise.  There is a plugin, PromisesPlugin, that says they rectifies this problem.  Do you recommend this plugin for Cordova apps are should I do something else??

The particular syntax problem is of the form .then((message) => { .  Your example will not build.

Thanks!
Howard

**Comment by hsmith825** [comment]
The es6-promise-plugin is installed.  For others that run into this problem, I get it to work with statements of the form:
ApplePay.canMakePayments()
    .then(function(message) {
        // Apple Pay is enabled and a supported card is setup. Expect:
        // 'This device can make payments and has a supported card'
          console.log(message);
        })
    .catch(function(message) {
        // There is an issue, examine the message to see the details, will be:
        // 'This device cannot make payments.''
        // 'This device can make payments but has no supported cards'
           console.log("message);
        });

**Comment by samkelleher** [comment]
Hi Howard,

Yes you're quite right.  It's not the Promise in the older webviews that might be the problem, but it is the [arrow functions](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) that is shown in my examples.

The two snippets below are functionally identical.

Works in modern devices, or JavaScript projects using a transpiler:
```
.then((payment) => { });
```

Used in older devices, or non-transpiled projects:
```
.then(function(payment) { });

**Comment by hsmith825** [comment]
Thanks!
