### ISSUE TITLE
Query: Paypal support

### ISSUE THREAD

**Issue by sudharsanmit** [samkelleher/cordova-plugin-applepay#9]
Does this plugin support Paypal?

**Comment by sudharsanmit** [comment]
Sorry. Bad question. Is there a dropin button for app integration like the way it is for Paypal?

**Comment by samkelleher** [comment]
The plugin just exposes the Apple Pay token, you can do whatever you need with it, such as passing it to second plugin or some of your own code to use with PayPal. So no, there is nothing here to drop in to enable PayPal support (I'm not even sure PayPal works with Apple Pay).
